#!/usr/bin/env python3
"""Validate the product source and generate the website data and shopping guide."""
import argparse
import datetime
import json
from pathlib import Path
import re
from urllib.parse import urlsplit, parse_qs

ROOT = Path(__file__).resolve().parents[1]
PARTS = set('helm visier hud brust schulter arm hand bein stiefel akku exo'.split())
STATUS = {'candidate': 'Kandidat', 'alternative': 'Option / Alternative', 'specification': 'Produktspezifikation offen'}

def validate(data, root=ROOT):
    if data.get('schema_version') != 1:
        raise ValueError('Unsupported catalog schema')
    datetime.date.fromisoformat(data['updated_on'])
    tag = data['affiliate']['amazon_de_tag']
    if not re.fullmatch(r'[a-z0-9-]+-21', tag):
        raise ValueError('Invalid Amazon DE tag')
    categories = [c['id'] for c in data['categories']]
    if len(categories) != len(set(categories)):
        raise ValueError('Duplicate category')
    ids = set()
    for p in data['products']:
        if not re.fullmatch(r'[a-z0-9-]+', p['id']) or p['id'] in ids:
            raise ValueError('Invalid or duplicate product ID')
        ids.add(p['id'])
        if p['category'] not in categories or p['status'] not in STATUS:
            raise ValueError('Unknown category/status')
        if p.get('price_eur') is not None:
            raise ValueError('Catalog does not contain verified price quotes')
        for key in ('name', 'compatibility', 'quantity_note'):
            if not isinstance(p[key], str) or not p[key].strip():
                raise ValueError('Missing product text')
        if not set(p['parts']).issubset(PARTS):
            raise ValueError('Unknown armor part')
        for guide in p['guides']:
            path = (root / guide).resolve()
            if not path.is_relative_to(root.resolve()) or not path.is_file() or path.suffix != '.md':
                raise ValueError('Missing/invalid guide: ' + guide)
        if not p['links']:
            raise ValueError('Product needs a source or search link')
        for link in p['links']:
            u = urlsplit(link['url'])
            if u.scheme != 'https' or not u.hostname or u.username or u.password or u.port not in (None, 443):
                raise ValueError('Unsafe source URL')
            if link['kind'] not in ('manufacturer', 'datasheet', 'search'):
                raise ValueError('Unknown source kind')
            amazon = u.hostname in ('amazon.de', 'www.amazon.de')
            params = parse_qs(u.query)
            if amazon:
                if not link['affiliate'] or link['kind'] != 'search' or u.path != '/s' or params.get('tag') != [tag] or not params.get('k'):
                    raise ValueError('Amazon must be a labelled, tagged search')
            elif link['affiliate'] or 'tag' in params:
                raise ValueError('Affiliate only supported for Amazon DE')
            if link['checked_on']:
                if link['kind'] == 'search':
                    raise ValueError('Search is not a verified offer')
                if datetime.date.fromisoformat(link['checked_on']) > datetime.date.fromisoformat(data['updated_on']):
                    raise ValueError('Source check cannot be in the future')
    return data

def outputs(data):
    encoded = json.dumps(data, ensure_ascii=True, indent=2).replace('<', '\\u003c')
    js = '// Generated by tools/suit_catalog.py. Edit Materials/ProductCatalog.json.\n'
    js += '(function(root) { var data = ' + encoded + ';\nif (typeof module === "object" && module.exports) module.exports = data;\nelse root.SuitProductData = data;\n})(typeof globalThis !== "undefined" ? globalThis : this);\n'
    lines = ['# Produktkatalog und Einkaufslinks', '', '<!-- Generated by tools/suit_catalog.py; edit Materials/ProductCatalog.json. -->', '',
             '[Interaktiven Produktkatalog oeffnen](../web/products/index.html)', '',
             'Herstellerquellen, technische Auswahlkriterien und Shop-Suchen fuer den konfigurierbaren Aufbau. Kandidaten sind nicht als Gesamtsystem erprobt. Alternativen nicht automatisch gemeinsam bestellen. Mengen sind Planungsangaben; finale CAD-Masse, Schnittstellen und reale Tests bestimmen die Auswahl.', '',
             '**Keine aktuellen Preisangebote:** Preise, Versand, Einfuhrkosten und Verfuegbarkeit im Shop pruefen. Bestehende Budgetbereiche sind Planungswerte. Eine Amazon-Suche bestaetigt weder Artikelidentitaet noch Kompatibilitaet.', '',
             '**Werbung / Affiliate:** ' + data['affiliate']['disclosure'], '',
             'Ein Quelldatum bezeichnet einen geprueften Seiteninhalt, keine Hardwarefreigabe. Ohne Datum steht die erneute Quellenpruefung aus.', '']
    for category in data['categories']:
        lines += ['## ' + category['label'], '', '| Produkt und Status | Auswahl / Menge | Quellen |', '| --- | --- | --- |']
        for p in data['products']:
            if p['category'] != category['id']:
                continue
            links = ' / '.join('[' + l['label'] + '](' + l['url'] + ')' + (' (Quelle: ' + l['checked_on'] + ')' if l['checked_on'] else '') for l in p['links'])
            guides = ' / '.join('[' + Path(g).stem + '](../' + g + ')' for g in p['guides'])
            lines += [f"| **{p['name']}** - {STATUS[p['status']]} | {p['compatibility']} Menge: {p['quantity_note']}. | {links}<br>{guides} |"]
        lines += ['']
    lines += ['## Pflege', '', 'Die zentrale Quelle ist [ProductCatalog.json](ProductCatalog.json). Nach Aenderungen `python tools/suit_catalog.py` im Repository ausfuehren. `--check` erkennt veraltete Ausgaben. Suchlinks bleiben Suchlinks; ungepruefte ASINs und Schaetzpreise werden nicht als Angebote veroeffentlicht.', '', 'Die Merkliste des Webkatalogs ist eine eigene Datei mit unbekannten Preisen (`null`). Sie ist kein Import fuer den Budgetplaner. Verifizierte Angebotspreise separat im Budgetplaner eintragen.', '']
    return {ROOT / 'web/products/catalog.js': js, ROOT / 'Materials/Einkaufsliste-Links.md': '\n'.join(lines)}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = validate(json.loads((ROOT / 'Materials/ProductCatalog.json').read_text()))
    for path, content in outputs(data).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale generated catalog: ' + str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print(f"Product catalog OK: {len(data['products'])} entries")

if __name__ == '__main__':
    main()
